while true do
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("gay", "All")
	wait(2)
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("I rape children", "All")
	wait(2)
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("gayshit shit", "All")
	wait(2)
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("fuck", "All")
	wait(2)
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("motherfucker bitch fucking nigger", "All")	
	wait(2)
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("GAY NIGGER ", "All")
	wait(2)
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("GAY BE LIKE HITLER MOTHERFUCKER DICK", "All")
	wait(2)
	game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("FUCKING BITCH PENIS VAGINA SIEG HEIL HITLER", "All")
	wait(2)
end
